stages:
  - check
  - build

nixfmt:
  stage: check
  needs: []
  tags:
    - nixos
  script:
    - just nixfmt --check

build:
  stages: build
  needs: []
  tags:
    - nixos
  parallel:
    matrix:
      - CONFIG:
          - cameron-laptop
          - server
      - NIXPKGS:
          - locked
          - latest
  script:
    - if [ "${NIXPKGS}" == "latest" ]; then just update; fi
    - just build ${CONFIG}
