image: nixos/nix:latest

stages:
  - check

before_script:
  - mkdir -p /etc/nix && echo "experimental-features = nix-command flakes" > /etc/nix/nix.conf
  - nix-env -i git just nixfmt

nixfmt:
  stage: check
  script:
    - just nixfmt --check
