stages:
  - check
  - build
  - latest

fmt:
  stage: check
  needs: []
  tags:
    - nixos
  script:
    - just fmt --check

build:
  stage: build
  needs: []
  tags:
    - nixos
  parallel:
    matrix:
      - CONFIG:
          - cameron-laptop
          - server
  script:
    - just build ${CONFIG} -L

latest:
  stage: latest
  needs: []
  tags:
    - nixos
  parallel:
    matrix:
      - CONFIG:
          - cameron-laptop
          - server
  script:
    - just update
    - just build ${CONFIG} -L
