image: nixos/nix:latest

stages:
  - check
  - build

before_script:
  - mkdir -p /etc/nix && echo "experimental-features = nix-command flakes" > /etc/nix/nix.conf
  - nix-env -i just git nixfmt

nixfmt:
  stage: check
  script:
    - just nixfmt --check

cameron-laptop:
  stage: build
  script:
    - just build cameron-laptop
