stages:
  - check
  - build
  - latest

nixfmt:
  stage: check
  needs: []
  tags:
    - nixos
  script:
    - just nixfmt --check

build:
  stage: build
  needs: []
  tags:
    - nixos
  parallel:
    matrix:
      - CONFIG:
          - cameron-laptop
          - server
  script:
    - just build ${CONFIG}

latest:
  stage: latest
  needs: []
  tags:
    - nixos
  parallel:
    matrix:
      - CONFIG:
          - cameron-laptop
          - server
  script:
    - just update
    - just build ${CONFIG}
