stages:
  - check
  - build
  - latest

nixfmt:
  stage: check
  needs: []
  tags:
    - nixos
  script:
    - just nixfmt --check

server:
  stage: build
  needs: []
  tags:
    - nixos
  script:
    - just build server

cameron-laptop:
  stage: build
  needs: []
  tags:
    - nixos
  script:
    - just build cameron-laptop

server-latest:
  stage: latest
  needs:
    - server
  tags:
    - nixos
  script:
    - nix flake lock --update-input nixpkgs
    - just build server

cameron-laptop-latest:
  stage: latest
  needs:
    - cameron-laptop
  tags:
    - nixos
  script:
    - nix flake lock --update-input nixpkgs
    - just build cameron-laptop
