# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "sg" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7477e30b-2304-4926-a87e-872afd793256";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6AE4-6D37";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8184073d-ed91-47f6-94db-e65e12867cba"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  environment.systemPackages = [ pkgs.mergerfs ];

  fileSystems = {
    "/drives/hdd-16tb-1" = {
      device = "/dev/disk/by-label/hdd-16tb-1";
      fsType = "ext4";
      options = [ "nofail" "x-systemd.device-timeout=10" ];
    };
    "/drives/hdd-16tb-2" = {
      device = "/dev/disk/by-label/hdd-16tb-2";
      fsType = "ext4";
      options = [ "nofail" "x-systemd.device-timeout=10" ];
    };
    "/drives/hdd-8tb-1" = {
      device = "/dev/disk/by-label/hdd-8tb-1";
      fsType = "ext4";
      options = [ "nofail" "x-systemd.device-timeout=10" ];
    };
    "/drives/hdd-8tb-2" = {
      device = "/dev/disk/by-label/hdd-8tb-2";
      fsType = "ext4";
      options = [ "nofail" "x-systemd.device-timeout=10" ];
    };
    "/data-1" = {
      device = "/drives/hdd-16tb-1:/drives/hdd-16tb-2";
      depends = [
        "/drives/hdd-16tb-1"
        "/drives/hdd-16tb-2"
      ];
      fsType = "fuse.mergerfs";
      options = [
        "direct_io"
        "defaults"
        "nofail"
        "allow_other"
        "category.create=ff"
        "minfreespace=50G"
        "fsname=mergerfs"
      ];
    };
    "/data-2" = {
      device = "/drives/hdd-8tb-1:/drives/hdd-8tb-2";
      depends = [
        "/drives/hdd-8tb-1"
        "/drives/hdd-8tb-2"
      ];
      fsType = "fuse.mergerfs";
      options = [
        "direct_io"
        "defaults"
        "nofail"
        "allow_other"
        "category.create=ff"
        "minfreespace=50G"
        "fsname=mergerfs"
      ];
    };
  };

}
